const catalogoInicial = [
  {
    id: 1,
    nombre: "Mario",
    apellido: "Gómez",
    matricula: 3456789,
    especialidad: "Dermatología",
    valorConsulta: 16000,
    email: "mario.gomez@saludintegral.com",
    telefono: "3414123456",
    obraSociales: ["OSDE", "Galeno"],
    descripcion: "El Dr. Mario Gómez se especializa en el tratamiento de enfermedades de la piel y realiza controles dermatológicos preventivos.",
    foto: "img/Cat_Doctor_1.png",
  },
  {
    id: 2,
    nombre: "Juan",
    apellido: "Pérez",
    matricula: 1234567,
    especialidad: "Cardiología",
    valorConsulta: 18000,
    email: "juan.perez@saludintegral.com",
    telefono: "3414234567",
    obraSociales: ["Swiss Medical", "OSDE"],
    descripcion: "El Dr. Pérez es especialista en enfermedades cardiovasculares y realiza estudios preventivos.",
    foto: "img/Cat_Doctor_2.png",
  },
  {
    id: 3,
    nombre: "Ana",
    apellido: "Torres",
    matricula: 9876543,
    especialidad: "Pediatría",
    valorConsulta: 16500,
    email: "ana.torres@saludintegral.com",
    telefono: "3414345678",
    obraSociales: ["Galeno", "OSDE"],
    descripcion: "La Dra. Torres se dedica a la atención integral de niños y adolescentes, priorizando la prevención.",
    foto: "img/Cat_Doctor_3.png",
  },
  {
    id: 4,
    nombre: "Carlos",
    apellido: "López",
    matricula: 1122334,
    especialidad: "Traumatología",
    valorConsulta: 17000,
    email: "carlos.lopez@saludintegral.com",
    telefono: "3414456789",
    obraSociales: ["OSDE", "Galeno"],
    descripcion: "El Dr. López se dedica a lesiones musculoesqueléticas y tratamientos traumatológicos.",
    foto: "img/Cat_Doctor_4.png",
  },
  {
    id: 5,
    nombre: "Sofía",
    apellido: "Ríos",
    matricula: 9988776,
    especialidad: "Ginecología",
    valorConsulta: 18000,
    email: "sofia.rios@saludintegral.com",
    telefono: "3414567890",
    obraSociales: ["Swiss Medical", "OSDE"],
    descripcion: "La Dra. Ríos ofrece atención ginecológica integral con enfoque en salud preventiva.",
    foto: "img/Cat_Doctor_5.png",
  },
  {
    id: 6,
    nombre: "Martín",
    apellido: "Silva",
    matricula: 5566778,
    especialidad: "Neurología",
    valorConsulta: 18000,
    email: "martin.silva@saludintegral.com",
    telefono: "3414678901",
    obraSociales: ["OSDE", "Galeno"],
    descripcion: "El Dr. Silva es especialista en patologías neurológicas y realiza evaluaciones preventivas.",
    foto: "img/Cat_Doctor_6.png",
  },
  {
    id: 7,
    nombre: "Carla",
    apellido: "Méndez",
    matricula: 2233445,
    especialidad: "Reumatología",
    valorConsulta: 16000,
    email: "carla.mendez@saludintegral.com",
    telefono: "3414789012",
    obraSociales: ["OSDE", "Swiss Medical"],
    descripcion: "La Dra. Méndez trabaja con terapia individual y grupal, enfocándose en bienestar emocional.",
    foto: "img/Cat_Doctor_7.png",
  },
  {
    id: 8,
    nombre: "Federico",
    apellido: "Ramos",
    matricula: 3344556,
    especialidad: "Endocrinología",
    valorConsulta: 12000,
    email: "federico.ramos@saludintegral.com",
    telefono: "3414890123",
    obraSociales: ["Galeno", "OSDE"],
    descripcion: "El Dr. Ramos trata trastornos hormonales y enfermedades metabólicas.",
    foto: "img/Cat_Doctor_8.png",
  },
  {
    id: 9,
    nombre: "Valeria",
    apellido: "Suárez",
    matricula: 4455667,
    especialidad: "Nutrición",
    valorConsulta: 14000,
    email: "valeria.suarez@saludintegral.com",
    telefono: "3414901234",
    obraSociales: ["OSDE", "Swiss Medical"],
    descripcion: "La Dra. Suárez realiza planes nutricionales personalizados y seguimiento de pacientes.",
    foto: "img/Cat_Doctor_9.png",
  },
  {
    id: 10,
    nombre: "Marcelo",
    apellido: "Ortiz",
    matricula: 5566779,
    especialidad: "Oftalmología",
    valorConsulta: 15800,
    email: "marcelo.ortiz@saludintegral.com",
    telefono: "3415012345",
    obraSociales: ["OSDE", "Galeno"],
    descripcion: "El Dr. Ortiz se especializa en cirugías y tratamientos de la visión.",
    foto: "img/Cat_Doctor_10.png",
  },
  {
    id: 11,
    nombre: "Lucía",
    apellido: "Fernández",
    matricula: 6677889,
    especialidad: "Reumatología",
    valorConsulta: 13000,
    email: "lucia.fernandez@saludintegral.com",
    telefono: "3415123456",
    obraSociales: ["Swiss Medical", "OSDE"],
    descripcion: "La Dra. Fernández trata enfermedades reumáticas y articulares, buscando mejorar la movilidad del paciente.",
    foto: "img/Cat_Doctor_11.png",
  },
  {
    id: 12,
    nombre: "Ricardo",
    apellido: "Medina",
    matricula: 7788990,
    especialidad: "Cirugía general",
    valorConsulta: 18000,
    email: "ricardo.medina@saludintegral.com",
    telefono: "3415234567",
    obraSociales: ["OSDE", "Galeno"],
    descripcion: "El Dr. Medina realiza cirugías y procedimientos quirúrgicos con enfoque en seguridad y recuperación rápida.",
    foto: "img/Cat_Doctor_12.png",
  },
  {
    id: 13,
    nombre: "Gabriela",
    apellido: "Díaz",
    matricula: 8899001,
    especialidad: "Endodoncia",
    valorConsulta: 17500,
    email: "gabriela.diaz@saludintegral.com",
    telefono: "3415345678",
    obraSociales: ["OSDE", "Swiss Medical"],
    descripcion: "La Dra. Díaz se dedica a tratamientos de conducto y cuidado integral de la salud dental.",
    foto: "img/Cat_Doctor_13.png",
  },
  {
    id: 14,
    nombre: "Alejandro",
    apellido: "Vargas",
    matricula: 9900112,
    especialidad: "Urología",
    valorConsulta: 15000,
    email: "alejandro.vargas@saludintegral.com",
    telefono: "3415456789",
    obraSociales: ["Galeno", "OSDE"],
    descripcion: "El Dr. Vargas se especializa en el diagnóstico y tratamiento de enfermedades del aparato urinario.",
    foto: "img/Cat_Doctor_14.png",
  },
  {
    id: 15,
    nombre: "Mariana",
    apellido: "López",
    matricula: 1011121,
    especialidad: "Fonoaudiología",
    valorConsulta: 14200,
    email: "mariana.lopez@saludintegral.com",
    telefono: "3415567890",
    obraSociales: ["OSDE", "Swiss Medical"],
    descripcion: "La Dra. López trabaja en la evaluación y rehabilitación de problemas de habla y comunicación.",
    foto: "img/Cat_Doctor_15.png",
  }
];